### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"  

### ISSUE THREAD

**Issue by xinyeDai** [xai-org/grok-1#102]
When I use this requirement, I encounter the following problem
"""
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" (from jax[cuda12-pip]) (from versions: 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.25)
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"  
"""
Then I changed the second line in requirement.txt from "jax[cuda12_pip]==0.4.25" to "jax[cuda12-pip]==0.4.25" which solved the problem.

**Comment by dev4ox** [comment]
use this commands
1. git clone https://github.com/google/jax.git
2. cd jax
3. pip install .

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108 

Related to #104

**Comment by 144358** [comment]
> 当我使用此要求时，我遇到以下问题“”“错误：找不到满足要求的版本 jaxlib==0.4.25+cuda12.cudnn89;extra == “cuda12_pip” （from jax[cuda12-pip]） （from versions： 0.4.13， 0.4.14， 0.4.16， 0.4.17， 0.4.18， 0.4.19， 0.4.20， 0.4.21， 0.4.22， 0.4.23， 0.4.25） 错误：找不到 jaxlib==0.4.25+cuda12.cudnn89 的匹配分布;extra == “cuda12_pip” “”“ 然后我把requirement.txt中的第二行从”jax[cuda12_pip]==0.4.25“改为”jax[cuda12-pip]==0.4.25“，解决了这个问题。

Thanks for your help, I also ran into this issue and then solved it using the same method

**Comment by sphenginx** [comment]
> When I use this requirement, I encounter the following problem """ ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" (from jax[cuda12-pip]) (from versions: 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.25) ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" """ Then I changed the second line in requirement.txt from "jax[cuda12_pip]==0.4.25" to "jax[cuda12-pip]==0.4.25" which solved the problem.

whatever，with the solution there is another warning： “WARNING: jax 0.4.25 does not provide the extra 'cuda12-pip'”
