### ISSUE TITLE
python 3.12.1   pip install requirement error

### ISSUE THREAD

**Issue by sherwoodrider** [xai-org/grok-1#106]
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" (from jax[cuda12-pip]) (from versions: 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.25)
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"

**Comment by dev4ox** [comment]
use this commands
1. git clone https://github.com/google/jax.git
2. cd jax
3. pip install .

**Comment by bluevisor** [comment]
You need a nvidia card and cuda driver (v12) installed first.
