### ISSUE TITLE
⚠️ 亲爱的新用户，请使用“讨论”功能来避免产生垃圾邮件打扰开发者 ⚠️ 

### ISSUE THREAD

**Issue by yxc0915** [xai-org/grok-1#108]
Github "Issues"旨在指出代码问题，例如错误或其他开发和运行相关问题、建议等。一般性会谈应在以下讨论中进行：

https://github.com/xai-org/grok-1/discussions

问题不是像 X 那样的地方，添加更多问题会导致垃圾问题。更多的噪音，更少的信号。因此，我恳请您关闭所有非问题并进行讨论，或者更好的是，如果它与使 grok-1 在系统或技术上工作无关，那么它最适合发布在 X 上。

这里有一位真正的工程师，他在 xAI 做一些很酷的事情，但添加垃圾邮件会降低他的工作效率，因为他必须关注 github 问题并关闭它们。请让他的生活轻松:)

-----转自问题#69

**Comment by bluevisor** [comment]
#69 亮了...

**Comment by DanielusG** [comment]
**comment off topic** 
_I don't understand why very often Chinese users don't use English in public repositories like this one. I could speak Italian, too, but instead..._

**Comment by zkna** [comment]
> > **comment off topic** _I don't understand why very often Chinese users don't use English in public repositories like this one. I could speak Italian, too, but instead..._
> 
> Probably because you are one of the great colonies of US but they are not (just kidding🤣, delete me)

haha

**Comment by Mydtlwn** [comment]
Because the Chinese language system differs from the Italian and American language systems, there may be distortions during translation, unlike between Italian and English. Additionally, the Chinese vocabulary is still expanding, and currently, many adults in China began learning English later in life, while some younger generations have started learning English earlier. @DanielusG

**Comment by millerhamburger** [comment]
[https://github.com/xai-org/grok-1/issues/69](url)

**Comment by ThreeManager785** [comment]
> **comment off topic** _I don't understand why very often Chinese users don't use English in public repositories like this one. I could speak Italian, too, but instead..._

I guess they're used to type Chinese

**Comment by hsmaocn** [comment]
> > **comment off topic** _I don't understand why very often Chinese users don't use English in public repositories like this one. I could speak Italian, too, but instead..._
> 
> I guess they're used to type Chinese

In fact, some people just come up here to have fun, (meaning they use it as a comment section for chatting) and don't have the sense to use the international common language, so just ignore such people and treat them as clowns. However, there are still quite a few Chinese users who are friendly.

**Comment by Xmabel112Lubi** [comment]
I am also of the opinion that English is everywhere, if I started to talk here in my native language, I would not succeed, despite everything, English is the basis everywhere in the world

Odoslané z aplikácie Outlook pre Android<https://aka.ms/AAb9ysg>
________________________________
