### ISSUE TITLE
If you want to run on gpu, use linux, if you have enough memory, both windows and linux will work, just grab your coffee,….

### ISSUE THREAD

**Issue by cheungxiongwei** [xai-org/grok-1#113]
![image](https://github.com/xai-org/grok-1/assets/22527245/c57317fe-4fa5-43f6-a7ce-452f5b74b474)

**Comment by bluevisor** [comment]
On M1 Mac:
INFO: pip is looking at multiple versions of jax[cuda12-pip] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" (from jax[cuda12-pip]) (from versions: 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25)
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"

**Comment by bluevisor** [comment]
I'll go try on my PC

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108
