### ISSUE TITLE
huggingface link

### ISSUE THREAD

**Issue by bluevisor** [xai-org/grok-1#118]
for the folks struggling with torrents:
https://huggingface.co/xai-org/grok-1/tree/main

maybe we should add this to the readme file?

**Comment by trholding** [comment]
See: https://github.com/xai-org/grok-1/discussions/129

Let's close this issue and move generic info to discussions?

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108

**Comment by bluevisor** [comment]
sure thing
