### ISSUE TITLE
Why is it impossible for python devs to add the python version to the docs? Let's discuss 

### ISSUE THREAD

**Issue by chrisbward** [xai-org/grok-1#121]
... for those of us that use pyenv or conda to avoid dependency issues

![Fo4i8_UWcAAZGZZ](https://github.com/openai/grok/assets/888374/b0c3429f-4472-4801-81e6-d80e81a4c133)

grok devs: "works for me"
![Laughing-Leo](https://github.com/openai/grok/assets/888374/3ff04901-b2b1-4a88-9910-87bfdd37baf0)

**Comment by Mydtlwn** [comment]
I think we should have a separate group of people establish a dedicated repository for discussing Grok, as some users prefer to raise issues. We can create such a repository and post its link here, pinning it as the first item in our current repository.

**Comment by chrisbward** [comment]
Reopen this issue please - the documentation needs to have the python version included.

**Comment by 778629322** [comment]
The link in the requirements.txt file is blocked by the firewall

https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
