### ISSUE TITLE
How to download checkpoint?

### ISSUE THREAD

**Issue by shanxianxin** [xai-org/grok-1#128]
How to download checkpoint?  I can not find this . It is a software?  or  model?

**Comment by trholding** [comment]
See: https://github.com/xai-org/grok-1/discussions/129

Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108

**Comment by shanxianxin** [comment]
> See: #129
> 
> Please close this issue and move to:
> 
> https://github.com/xai-org/grok-1/discussions
> 
> Reason: #69 #108

i know how to download the code of grok1. My problem about checkpoint! Because grok work need checkpoint before.

**Comment by trholding** [comment]
This should work:

```
git clone https://github.com/xai-org/grok-1.git
cd grok-1/checkpoints
```

Then download the checkpoints via torrent or from hugginface as in https://github.com/xai-org/grok-1/discussions/129 and place ckpt directory (https://huggingface.co/xai-org/grok-1/tree/main/ckpt) into grok-1/checkpoints

Then do:

```
cd ..
pip install -r requirements.txt
python run.py
```
