### ISSUE TITLE
Grok implementation details

### ISSUE THREAD

**Issue by andrewgcodes** [xai-org/grok-1#14]
not an issue but would be nice if it was in the readme/model.py header:
314B parameters
Mixture of 8 Experts
2 experts used per token
64 layers
48 attention heads for queries
8 attention heads for keys/values
embeddings size: 6,144
rotary embeddings (RoPE)
SentencePiece tokenizer; 131,072 tokens
Supports activation sharding and 8-bit quantization
Max seq length (context): 8,192 tokens

**Comment by garethpaul** [comment]
@morozover you can find most of the values in https://github.com/xai-org/grok-1/blob/e50578b5f50e4c10c6e7cff31af1ef2bedb3beb8/run.py#L33

Additional see Rotary Embedding implementation @ https://github.com/xai-org/grok-1/blob/e50578b5f50e4c10c6e7cff31af1ef2bedb3beb8/model.py#L635

**Comment by Konard** [comment]
@andrewgcodes since it is merged at https://github.com/xai-org/grok-1/pull/27, I think this issue can be closed.
