### ISSUE TITLE
Please provide minimal hardware requirement

### ISSUE THREAD

**Issue by leicao-me** [xai-org/grok-1#165]
It seems that 1 GPU and single machine instance doesn't work. I got an error indicating RAM is not enough and vRAM also don't have enough space. I was manage to change the GPU device mesh in run.py from (1, 8) to (1, 1), but it doesn't help. 

Please provide minimal hardware/cluster requirement. Thank you.

**Comment by Konard** [comment]
I have already asked that question here: https://github.com/xai-org/grok-1/issues/62

**Comment by xSetech** [comment]
Dup #62
