### ISSUE TITLE
The weights too big !!!

### ISSUE THREAD

**Issue by leavestyle-coder** [xai-org/grok-1#184]
<img width="191" alt="截屏2024-03-19 13 12 37" src="https://github.com/xai-org/grok-1/assets/25811040/e508410e-b81d-460e-abb7-90786c30b38e">

OMG.....

**Comment by trholding** [comment]
LLM Models are usually large. grok-1 is one of the largest. Hence it is a huge download. Also the system requires 8 GPUs with a total memory (VRAM) that is larger than the model size to run.

Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
Not a real issue
#69 
#108
