### ISSUE TITLE
How to run grok on macbook m1？

### ISSUE THREAD

**Issue by wenkikro** [xai-org/grok-1#188]
As a student, without a high-performance running environment, can you provide a solution or suggestion for running grok on a macbook m1?

**Comment by whb883** [comment]
wow，macbook ～！you idea is too fanciful

**Comment by lomar999** [comment]
no way

**Comment by nesimtunc** [comment]
Probably you'll need a GPU farm :D

**Comment by tyrantGXY** [comment]
不可能啦，毕竟千亿参数。

**Comment by weiccTest** [comment]
目前是不行的

**Comment by wenkikro** [comment]
It feels like the large model is very close, but in reality it is very far, very far, so far that you can only use the API, you can't run it yourself, the cost is too expensive.

**Comment by SanjayJinderPatel** [comment]
I tried running this on my soybook and it was saying not working bloody
