### ISSUE TITLE
Enable Discussions tab on this GitHub repo

### ISSUE THREAD

**Issue by EwoutH** [xai-org/grok-1#20]
I would find it quite useful if the [Discussions](https://github.com/features/discussions) tab could be enabled on this repository. Then users would have a place to discuss questions, configurations and new ideas, without adding noise here in the issues.

It can be enabled very easily, see [Enabling GitHub Discussions on your repository](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository).

**Comment by ibab** [comment]
Done, thank you.
