### ISSUE TITLE
download the weights failed according to the readme file: zsh: no matches found: ckpt-0/*

### ISSUE THREAD

**Issue by yuezhongtao** [xai-org/grok-1#203]
grok-1 % huggingface-cli download xai-org/grok-1 --repo-type model --include ckpt-0/* --local-dir checkpoints --local-dir-use-symlinks False

zsh: no matches found: ckpt-0/*

**Comment by yuezhongtao** [comment]
<img width="984" alt="image" src="https://github.com/xai-org/grok-1/assets/18341274/c8e297cc-5712-47a4-91b8-4db0ead16e0d">

**Comment by trholding** [comment]
https://github.com/xai-org/grok-1/issues/203#issuecomment-2007003097 is the correct answer.

Please see: https://github.com/xai-org/grok-1/discussions/129

Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
User's shell issue / Not a real issue
#69 
#108
