### ISSUE TITLE
Whether the model is a base model or a chat model?

### ISSUE THREAD

**Issue by LaoWangGB** [xai-org/grok-1#206]
Whether the Model is a base model or chat model?
If it's a chat model, what's the chat format? same as closeAI?

**Comment by gokhangerdan** [comment]
"This is the raw base model checkpoint from the Grok-1 pre-training phase, which concluded in October 2023. This means that the model is not fine-tuned for any specific application, such as dialogue."
Source: https://x.ai/blog/grok-os

**Comment by xSetech** [comment]
Answered here: https://x.ai/blog/grok-os
