### ISSUE TITLE
how to make my personal ai chatbot now with this grok

### ISSUE THREAD

**Issue by good1uck** [xai-org/grok-1#218]
i have a normal Game PC , can i make it and how to make it

**Comment by WindC00** [comment]
It is not suitable for personal computers, because at least 8 GPUs are needed.
[#183 ](https://github.com/xai-org/grok-1/discussions/183)

**Comment by atgsmsg** [comment]
H100 SXM5 NVLink GPU x 8
$34,000.00 each ($272,000.00)

AMD 100-000000802 EPYC 9124 Genoa 9004 Series 16-core 3 GHz Server Processor × 2
$1,111.00 each (2,222.00)

24 x 64GB DDR5 4800 ECC Reg Server Compatible Memory Kit (1.5TB Total)
$8,280.00

Micron MTFDKCB960TFR-1BC1ZABYYR 7450 PRO 960 GB Solid State Drive - 2.5" Internal - U.3 (PCI Express NVMe 4.0 x4) - Read Intensive - TAA Compliant
$142.00 each

total $297,019.00 (without station/power units)
