### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by chenyzh28** [xai-org/grok-1#231]
I installed dm_haiku==0.0.12 according to the requirements. But I met some errors when I run 'python run.py'. I found that the haiku import has some problem. Why is that? I didn't find any solution.
<img width="706" alt="69BC42D6-85B1-4236-8613-6252A8B22226" src="https://github.com/xai-org/grok-1/assets/35193979/2cc13ed4-1624-47b0-b758-eecd8bdb534b">

**Comment by wweevv-johndpope** [comment]
python 3.8? ??? you need to bump that to 3.11

**Comment by chenyzh28** [comment]
> python 3.8? ??? you need to bump that to 3.11

It has to be 3.11?

**Comment by chenyzh28** [comment]
The env has to be python3.11+cuda12.3+cudnn8.9+jax[cuda12_pip]==0.4.23, otherwise there will be some errors.
