### ISSUE TITLE
Anyone was able to run this on their PC on Windows?

### ISSUE THREAD

**Issue by yarodevuci** [xai-org/grok-1#25]
Trying to run this on Windows, getting tons of errors...
Also, what GPU card is the min requirement for this ?

**Comment by nichind** [comment]
apparently it needs 8GPU (80gb vram) to run

**Comment by Bordo2000** [comment]
You'll need to download the 300GB weights files using a torrent client if you have the space and time have fun. I would recommend using qBittorrent since it's open-source.

**Comment by cybershrapnel** [comment]
i have two 3090s and a 4060 and a 3060.... I don't see this happening lol
and that 4 4090s you would need fyi :P

**Comment by Qu3tzal** [comment]
> > apparently it needs 8 GPU (80GB vram) to run
> 
> Say less. That's 3x 4090s.

No, it's not 80GB VRAM total, it's 8 GPU with 80 GB VRAM each (typically A100s). 4x 4090s, would barely be enough to contain the model's weights in VRAM at 4-bits quant, not run it (that is if not loading/unloading from CPU).

**Comment by cybershrapnel** [comment]
80gb each, well fml

**Comment by cybershrapnel** [comment]
so we need to start a project to get this thing broken down and running on petals

**Comment by Hakureirm** [comment]
Apparently not.

**Comment by zcobol** [comment]
The weights can be downloaded w/out a torrent client at https://academictorrents.com/details/5f96d43576e3d386c9ba65b883210a393b68210e

**Comment by metatron1973** [comment]
Nice to meet all the active people

**Comment by yongatgithub** [comment]
> > > apparently it needs 8 GPU (80GB vram) to run
> > 
> > 
> > Say less. That's 3x 4090s.
> 
> No, it's not 80GB VRAM total, it's 8 GPU with 80 GB VRAM each (typically A100s). 4x 4090s, would barely be enough to contain the model's weights in VRAM at 4-bits quant, not run it (that is if not loading/unloading from CPU).

The hardware to run this is nuts. A100 costs around $12k each if you can find one. Just thinking about the PCIe expanders to connect all of them up on a motherboard gives me goosebumps. NVIDIA DGX Station with 4 x A100 GPU starts around $120k  Please post if anyone is actually trying this, but this is way beyond most people.

**Comment by tommyming** [comment]
I think for a language model at this size, GPU workstations are needed to make it run smoothly. So yeah, you have a pay a lot to run this.

**Comment by yarodevuci** [comment]
INFO:rank:(1, 256, 6144)
INFO:rank:(1, 256, 131072)
INFO:rank:State sharding type: <class 'model.TrainingState'>
INFO:rank:(1, 256, 6144)
INFO:rank:(1, 256, 131072)
INFO:rank:Loading checkpoint at ./checkpoints/ckpt-0

it hanks on the last line....

**Comment by N9ne-Bytes** [comment]
GPU:
- Minimum: NVIDIA A100 GPU with 40GB HBM2 VRAM
- Recommended: NVIDIA A100 GPU with 80GB HBM2 VRAM or higher

CPU:
- Minimum: AMD Ryzen Threadripper 3990X (64 cores, 128 threads)
- Recommended: AMD EPYC 7763 (64 cores, 128 threads) or higher

RAM:
- Minimum: 128GB DDR4 ECC RDIMM
- Recommended: 256GB DDR4 ECC RDIMM or higher

Storage:
- Minimum: 2TB NVMe SSD for storing the model weights
- Recommended: 4TB NVMe SSD or higher

**Comment by yarodevuci** [comment]
TypeError: dynamic_update_slice update shape must be smaller than operand shape, got update shape (1,) for operand shape (0,).

**Comment by innat** [comment]
How about running it on TPU (v4 or v5)?

**Comment by amao12580** [comment]
8 x H100（80GB）

**Comment by Imsovegetable** [comment]
> How about running it on TPU (v4 or v5)?

How to get TPU for most people?

**Comment by Qu3tzal** [comment]
> > How about running it on TPU (v4 or v5)?
> 
> How to get TPU for most people?

Google Colab Pro+

**Comment by Qu3tzal** [comment]
> > > > apparently it needs 8 GPU (80GB vram) to run
> > > 
> > > 
> > > Say less. That's 3x 4090s.
> > 
> > 
> > No, it's not 80GB VRAM total, it's 8 GPU with 80 GB VRAM each (typically A100s). 4x 4090s, would barely be enough to contain the model's weights in VRAM at 4-bits quant, not run it (that is if not loading/unloading from CPU).
> 
> The hardware to run this is nuts. A100 costs around $12k each if you can find one. Just thinking about the PCIe expanders to connect all of them up on a motherboard gives me goosebumps. NVIDIA DGX Station with 4 x A100 GPU starts around $120k Please post if anyone is actually trying this, but this is way beyond most people.

Yeah I mean 314B is a crazy amount of parameters. This might be useful for big companies that have the resources to use it's clearly not aimed at individuals (at least not with current's consumer hardware).

**Comment by imannms000** [comment]
> > > apparently it needs 8 GPU (80GB vram) to run
> > 
> > 
> > Say less. That's 3x 4090s.
> 
> No, it's not 80GB VRAM total, it's 8 GPU with 80 GB VRAM each (typically A100s). 4x 4090s, would barely be enough to contain the model's weights in VRAM at 4-bits quant, not run it (that is if not loading/unloading from CPU).

Source? Trust me bro?

**Comment by DarkInsider** [comment]
I saw in a tweeter they said it using just 2 out of 8 experts simultaneously, so probably it will not require 300+ GB of VRAM, just 75 or so
Also if it will be quantized to lower size might even fit in 24GB

**Comment by bluevisor** [comment]
> I saw in a tweeter they said it using just 2 out of 8 experts simultaneously, so probably it will not require 300+ GB of VRAM, just 75 or so Also if it will be quantized to lower size might even fit in 24GB

you mean these lines in the run.py?
`            # MoE.
            num_experts=8,
            num_selected_experts=2,`

**Comment by davidearlyoung** [comment]
> I saw in a tweeter they said it using just 2 out of 8 experts simultaneously, so probably it will not require 300+ GB of VRAM, just 75 or so Also if it will be quantized to lower size might even fit in 24GB

I think the whole model still needs to be loaded into memory still. Even if routing for inference is only using 2 of the 8 experts for a forward pass.

**Comment by yarodevuci** [comment]
> I gave up

same, it's unreal in the home environment.. and even if we do run it, it's useless, since it's not fine-tuned or anything to use.

**Comment by StavrosD** [comment]
Grok uses jaxlib. There are no windows wheels for jax + cuda so it is better to stick on linux, unless you want to develop and manually compile jax.

**Comment by davidearlyoung** [comment]
> Grok uses jaxlib. There are no windows wheels for jax + cuda so it is better to stick on linux, unless you want to develop and manually compile jax.

I was curious about jax in regards of playing nice with everything else in the open source community. My knowledge is small in regards of jax in particular. Good to know about this little bit.

I've been watching things unfold here out of curiosity and amusement. Might as well since I can't run it. Knew this was the case the moment I saw the parameter count near announcements.

One side note/thought/musing from me in regard of all this: I was a bit surprised to see jax being used with Grok-1. I'd assumed it likely was going to be in format/framework that worked with/for pytorch.
Think that many may have better luck with running Grok once it's moved to pytorch. Which is a more familiar system for the open community.

**Comment by youngmmmqing** [comment]
Nice to meet you all. 
Have you used it successfully?

**Comment by Qu3tzal** [comment]
> I was a bit surprised to see jax being used with Grok-1.

If you're going to rebuild everything from scratch, JAX is an excellent choice. JAX was made to be fast and distributed on big compute power. PyTorch is only catching up recently with `compile()` and `functorch`.

**Comment by davidearlyoung** [comment]
> > I was a bit surprised to see jax being used with Grok-1.
> 
> If you're going to rebuild everything from scratch, JAX is an excellent choice. JAX was made to be fast and distributed on big compute power. PyTorch is only catching up recently with `compile()` and `functorch`.

Those are interesting points. Thanks for sharing.

It sounds like someone may have grok running, as is from this repo, on multiple A100's. (https://github.com/xai-org/grok-1/discussions/168) Looks to be a bit slow output rate wise. But likely to get better as things publicly become more understood about it.

**Comment by StavrosD** [comment]
@yarodevuci 

You can enable Linux subsystem for windows and use WSL to run it. It is linux inside windows, you can do everything you want and CUDA can use the GPUs installed in windows. 

I just installed the requirements successfully. I cannot run because I do not have enough VRAM (just 2 x 24GB). 
When I run "python run.py" I get the error "ValueError: Number of devices 2 must equal the product of mesh_shape (1, 8)" so I assume that by default you need 8 GPUs to load the model.

**Comment by davidearlyoung** [comment]
I found this. Though likely a different subject from this thread title. It's some what related due to earlier side conversation about grok and pytorch: https://github.com/dominiquegarmier/grok-pytorch

**Comment by davidearlyoung** [comment]
In relation to my last comment, I also found this: https://huggingface.co/hpcai-tech/grok-1
Having things in pytorch will likely help with getting the model running. Due to the open community mostly being familiar with python+pytorch.

**Comment by loginbug01** [comment]
Will there be a castrated version similar to 7B in the future? I really hope it runs on the 4060ti 16g, which might be more popular with casual users

**Comment by Qu3tzal** [comment]
> Will there be a castrated version similar to 7B in the future?

The 7B space of models is already well furnished. They don't seem interested in spending time open-sourcing 7B or consumer size models.

**Comment by jifa513** [comment]
> TypeError: dynamic_update_slice update shape must be smaller than operand shape, got update shape (1,) for operand shape (0,).

+1
