### ISSUE TITLE
No such a directory 'Dev'

### ISSUE THREAD

**Issue by spacewalk01** [xai-org/grok-1#255]
Hi thank you for opensourcing your model. However, I got the following error when I run run.py:

`FileNotFoundError: [Errno 2] No such file or directory: 'D:\\dev\\shm\\tmpqye6hukj'`

Note that I am running it on a windows machine. Thanks.

**Comment by yangjiandan** [comment]
update checkpoint.py:50 may fix this error
`-    tmp_dir = "/dev/shm/"
+    tmp_dir = "/tmp/shm/"`

**Comment by Vysokostnyi** [comment]
these 2 functions can be changed for windows

update checkpoint.py

@contextlib.contextmanager
def copy_to_shm(file: str):
    tmp_dir = tempfile.gettempdir()
    fd, tmp_path = tempfile.mkstemp(dir=tmp_dir)
    try:
        shutil.copyfile(file, tmp_path)
        yield tmp_path
    finally:
        os.close(fd)
        os.remove(tmp_path)

@contextlib.contextmanager
def copy_from_shm(file: str):
    tmp_dir = tempfile.gettempdir()
    fd, tmp_path = tempfile.mkstemp(dir=tmp_dir)
    try:
        yield tmp_path
        shutil.copyfile(tmp_path, file)
    finally:
        os.close(fd)
        os.remove(tmp_path)
