### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by SleepTheGod** [xai-org/grok-1#263]
root@localhost:~# pip install huggingface_hub[hf_transfer]
Collecting huggingface_hub[hf_transfer]
  Downloading huggingface_hub-0.21.4-py3-none-any.whl.metadata (13 kB)
Collecting filelock (from huggingface_hub[hf_transfer])
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_transfer]) (2024.3.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_transfer]) (2.31.0)
Collecting tqdm>=4.42.1 (from huggingface_hub[hf_transfer])
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub[hf_transfer]) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub[hf_transfer]) (4.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/lib/python3/dist-packages (from huggingface_hub[hf_transfer]) (23.0)
Collecting hf-transfer>=0.1.4 (from huggingface_hub[hf_transfer])
  Downloading hf_transfer-0.1.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[hf_transfer]) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[hf_transfer]) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[hf_transfer]) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[hf_transfer]) (2022.9.24)
Downloading hf_transfer-0.1.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 70.0 MB/s eta 0:00:00
Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 34.8 MB/s eta 0:00:00
Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading huggingface_hub-0.21.4-py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.4/346.4 kB 99.3 MB/s eta 0:00:00
Installing collected packages: tqdm, hf-transfer, filelock, huggingface_hub
Successfully installed filelock-3.13.1 hf-transfer-0.1.6 huggingface_hub-0.21.4 tqdm-4.66.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@localhost:~# huggingface-cli download xai-org/grok-1 --repo-type model --include ckpt-0/* --local-dir checkpoints --local-dir-use-symlinks False
Consider using `hf_transfer` for faster downloads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
Fetching 770 files:   0%|                                                                       | 0/770 [00:00<?, ?it/s]downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00002_000 to /root/.cache/huggingface/hub/tmppb83jbz3
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 1611.14 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 1611.14 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 1611.14 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00000_000 to /root/.cache/huggingface/hub/tmpy5zglaw1
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 3221.23 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 3221.23 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 3221.23 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00005_000 to /root/.cache/huggingface/hub/tmpamgz3s29
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 6.29 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 6.29 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 6.29 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00003_000 to /root/.cache/huggingface/hub/tmp_sygdtxi
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 1611.40 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 1611.40 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 1611.40 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00006_000 to /root/.cache/huggingface/hub/tmp4a1kx05z
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 37.85 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 37.85 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 37.85 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00004_000 to /root/.cache/huggingface/hub/tmp_f2ke5v8
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00007_000 to /root/.cache/huggingface/hub/tmp98bpxglv
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 37.76 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 37.76 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 37.76 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00001_000 to /root/.cache/huggingface/hub/tmp2huv5uv3
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 0.02 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 0.02 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 0.02 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
ckpt-0/tensor00005_000: 100%|██████████████████████████████████████████████████████| 6.29M/6.29M [00:00<00:00, 88.3MB/s]
ckpt-0/tensor00005_000:   0%|                                                               | 0.00/6.29M [00:00<?, ?B/sdownloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00008_000 to /root/.cache/huggingface/hub/tmpnn5d87mt                                        | 10.5M/3.22G [00:00<00:30, 104MB/s]
ckpt-0/tensor00001_000: 100%|██████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 61.7MB/s]
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00009_000 to /root/.cache/huggingface/hub/tmpov2zl6gb
ckpt-0/tensor00008_000: 100%|██████████████████████████████████████████████████████| 6.29M/6.29M [00:00<00:00, 95.6MB/s]
ckpt-0/tensor00009_000: 100%|██████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 2.34MB/s]
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00010_000 to /root/.cache/huggingface/hub/tmps6f7w0of                                      | 21.0M/3.22G [00:00<00:36, 88.2MB/s]
ckpt-0/tensor00010_000: 100%|██████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 82.9MB/s]
ckpt-0/tensor00001_000:   0%|                                                               | 0.00/24.7k [00:00<?, ?B/s]
ckpt-0/tensor00009_000:   0%|                                                               | 0.00/24.7k [00:00<?, ?B/s]
ckpt-0/tensor00004_000:   1%|▋                                                      | 21.0M/1.61G [00:00<00:15, 105MB/s]

ckpt-0/tensor00010_000:   0%|                                                               | 0.00/24.7k [00:00<?, ?B/s]
ckpt-0/tensor00012_000: 100%|███████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 104MB/s]
ckpt-0/tensor00011_000: 100%|██████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 89.6MB/s]
ckpt-0/tensor00000_000:   1%|▌                                                     | 31.5M/3.22G [00:00<00:34, 93.7MB/sdownloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00013_000 to /root/.cache/huggingface/hub/tmpbxk_xy8n███████████████▍                        | 21.0M/37.8M [00:00<00:00, 127MB/s]
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 0.20 MB. The target location /root/.cache/huggingface/hub only has 0.00 MB free disk space.
  warnings.warn(03_000:   1%|▋                                                     | 21.0M/1.61G [00:00<00:16, 97.9MB/s]
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 0.20 MB. The target location /root/.cache/huggingface/hub/models--xai-org--grok-1/blobs only has 0.00 MB free disk space.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py:1006: UserWarning: Not enough free disk space to download the file. The expected file size is: 0.20 MB. The target location checkpoints only has 0.00 MB free disk space.
  warnings.warn(
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00014_000 to /root/.cache/huggingface/hub/tmpse4hxpz5
ckpt-0/tensor00013_000: 100%|█████████████████████████████████████████████████████████| 197k/197k [00:00<00:00, 270MB/s]
                                                                                                                       downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00015_000 to /root/.cache/huggingface/hub/tmp486m5xvi
ckpt-0/tensor00006_000: 100%|██████████████████████████████████████████████████████| 37.8M/37.8M [00:00<00:00, 98.7MB/s]
ckpt-0/tensor00007_000: 100%|██████████████████████████████████████████████████████| 37.8M/37.8M [00:00<00:00, 88.3MB/s]
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00016_000 to /root/.cache/huggingface/hub/tmpz6mo33z2                                      | 52.4M/3.22G [00:00<00:31, 99.9MB/s]
ckpt-0/tensor00007_000:  83%|████████████████████████████████████████████▉         | 31.5M/37.8M [00:00<00:00, 96.1MB/sdownloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00017_000 to /root/.cache/huggingface/hub/tmp_pr543ok                                       | 31.5M/1.61G [00:00<00:16, 93.3MB/s]
ckpt-0/tensor00017_000: 100%|███████████████████████████████████████████████████████| 6.29M/6.29M [00:00<00:00, 127MB/s]
ckpt-0/tensor00002_000:   4%|██▏                                                    | 62.9M/1.61G [00:00<00:13, 112MB/sdownloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00018_000 to /root/.cache/huggingface/hub/tmpl8im6vh1                                       | 41.9M/1.61G [00:00<00:17, 88.3MB/s]
ckpt-0/tensor00018_000: 100%|██████████████████████████████████████████████████████| 37.8M/37.8M [00:00<00:00, 60.1MB/s]
ckpt-0/tensor00002_000:   7%|███▋                                                    | 105M/1.61G [00:01<00:15, 100MB/sdownloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00019_000 to /root/.cache/huggingface/hub/tmpo8pd3n67                                        | 115M/1.61G [00:01<00:19, 74.8MB/s]
ckpt-0/tensor00004_000:   8%|████▎                                                  | 126M/1.61G [00:01<00:17, 83.2MB/s]
ckpt-0/tensor00019_000:  28%|██████████████▉                                       | 10.5M/37.8M [00:00<00:00, 81.3MB/s]
ckpt-0/tensor00000_000:   4%|██▏                                                    | 126M/3.22G [00:01<00:39, 79.0MB/s]
Fetching 770 files:   0%|                                                                       | 0/770 [00:01<?, ?it/s]
ckpt-0/tensor00002_000:   8%|████▋                                                  | 136M/1.61G [00:01<00:16, 88.9MB/s]
ckpt-0/tensor00014_000:   7%|███▉                                                   | 115M/1.61G [00:01<00:15, 96.6MB/s]
ckpt-0/tensor00015_000:   7%|███▌                                                   | 105M/1.61G [00:01<00:16, 91.9MB/s]
ckpt-0/tensor00016_000:   6%|███▏                                                  | 94.4M/1.61G [00:01<00:16, 94.3MB/s]
ckpt-0/tensor00003_000:   8%|████▋                                                  | 136M/1.61G [00:01<00:16, 91.3MB/s]
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00021_000 to /root/.cache/huggingface/hub/tmpm5ov9dgn                                       | 115M/1.61G [00:01<00:15, 98.3MB/s]
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00022_000 to /root/.cache/huggingface/hub/tmpx1l3300j
ckpt-0/tensor00021_000: 100%|██████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 93.0MB/s]
ckpt-0/tensor00022_000: 100%|██████████████████████████████████████████████████████| 24.7k/24.7k [00:00<00:00, 24.2MB/s]
downloading https://huggingface.co/xai-org/grok-1/resolve/e32dd0d967cf0bb60ebb976c47950693d12d5108/ckpt-0/tensor00020_000 to /root/.cache/huggingface/hub/tmpibqwuu_p
ckpt-0/tensor00020_000: 100%|███████████████████████████████████████████████████████| 6.29M/6.29M [00:00<00:00, 493MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/commands/huggingface_cli.py", line 49, in main
    service.run()
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/commands/download.py", line 160, in run
    print(self._download())  # Print path to downloaded files
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/commands/download.py", line 201, in _download
    return snapshot_download(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "/usr/local/lib/python3.11/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py", line 1492, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.11/dist-packages/huggingface_hub/file_download.py", line 550, in http_get
    temp_file.write(chunk)
  File "/usr/lib/python3.11/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device
root@localhost:~#

**Comment by xSetech** [comment]
what
