### ISSUE TITLE
Remove coppersurfer tracker

### ISSUE THREAD

**Issue by BitesizedLion** [xai-org/grok-1#34]
The tracker `tracker.coppersurfer.tk` should be removed from the magnet link in the README.

It is no longer a working bittorrent tracker, instead the domain redirects to a parking page.

**Comment by Konard** [comment]
@BitesizedLion you may try to open pull request about that to help X AI developers. But I was not able to check that torrent tracker myself.

**Comment by BitesizedLion** [comment]
> @BitesizedLion you may try to open pull request about that to help X AI developers. But I was not able to check that torrent tracker myself.
@Konard 

What was the point of this comment? You didn't contribute with anything, I made it an issue for a reason.

```
❯ whois coppersurfer.tk
The domain you requested is not known in Freenoms database.
```

```
❯ ipinfo coppersurfer.tk
- IP: 103.224.182.246
- Hostname: lb-182-246.above.com
- Organization: AS133618 Trellian Pty. Limited
```
As you can see this IP belongs to Above.com, which provides Domain Parking services, you can even try resolving the `tracker.coppersurfer.tk` subdomain and you'll get the same thing.

And if you try reaching it at port 6969 you can't reach it either, for obvious reasons mentioned above.
