### ISSUE TITLE
Phishing Scheme or Job Interview?

### ISSUE THREAD

**Issue by Bhaney44** [xai-org/grok-1#349]
Hi,

I hope all is well. I received a request regarding a job at xAI to which I had applied. I clicked the link to take the test, but it consistently failed, even with different browsers. 

The email provided no method to reply. But, I did apply to the job and it was from the official x.ai domain as far as I can tell. I would certainly like to take the test for the opportunity. 

<img width="853" alt="Screen Shot 2024-07-15 at 8 42 27 PM" src="https://github.com/user-attachments/assets/caeb7b71-eec2-4a93-bd22-305a3a701978">

However, given the problem with the link and there being no way to reply, I am worried this is a phishing scheme. I wanted to reach out some way to xAI to verify if possible. However, there is no way to connect that I know of, other than to post here.

Any thoughts, suggestions, or advice would be appreciated.

Thanks,

Brian

**Comment by DoneByAP** [comment]
Legit

**Comment by Xmabel112Lubi** [comment]
Hi can I ask if it's Possible permission testing Grok for free in my country thanks
