### ISSUE TITLE
We need 4 to 5 H100 GPUs to run the whole thing, Imao!!!

### ISSUE THREAD

**Issue by raghu-007** [xai-org/grok-1#36]

**Comment by zztonys** [comment]
haha, reasonable

**Comment by Abecid** [comment]
Lmao GPU poors ngmi

**Comment by metatron1973** [comment]
That's a good thing he went over and beyond ....![image](https://github.com/xai-org/grok-1/assets/80199202/a022ac53-9b9a-4c51-b882-f65760b17036)

**Comment by runvnc** [comment]
Has anyone confirmed a configuration that can run it? Such as on AWS, RunPod, or anything? Or just any verified test or demo of it ever being run outside of x.ai, and any info on the configuration used to achieve that? Another comment suggested 8 x A100.
