### ISSUE TITLE
Could you provide hugging face version so that we can run in huggingface space. 

### ISSUE THREAD

**Issue by deerleo** [xai-org/grok-1#40]
Not quite sure whether huggingface's gpu match the requirements. If it works, could you provide a huggingface version? Thank you !

**Comment by trholding** [comment]
Info: 
grok-1 on huggingface: https://huggingface.co/xai-org/grok-1
Discussion about conversion to huggingface safetensors: https://huggingface.co/xai-org/grok-1/discussions/13

**Comment by deerleo** [comment]
Thank you
