### ISSUE TITLE
Opensource training pipeline

### ISSUE THREAD

**Issue by trholding** [xai-org/grok-1#43]
Dear xAI team

Would xAI consider opensourcing the training pipleline or recipe to reproduce models? As I understand the weights and inference part is open. Arguably this is not fully opensource.

The benefits of open sourcing the training pipeline is mutual, researches could experiment and contribute to a more effective training pipeline or model improvements... xAI could benefit from that to get more market share and be the true Open AI!

**Comment by furkanmustafa** [comment]
The word used "open" or the license chosen (Apache) probably only talking about the python codes in the repository.

Model files shared like this could only be "[freeware](https://en.wikipedia.org/wiki/Freeware)". Reaching open source models would be a far target. But at least training sources could have been credited, to have just a bit of openness. Current level of "open"ness is 0% I would say :D (I'm thankful for freeware availability though)

**Comment by Konard** [comment]
That will also enable to develop downsized versions of that model, to enable wider audience to participate in research and experiments. It also would be nice to have answers about the [grok's dataset](https://github.com/xai-org/grok-1/issues/61).

**Comment by trholding** [comment]
This will move to discussions
