### ISSUE TITLE
Can I rent a GPU from a cloud server vendor to run it?

### ISSUE THREAD

**Issue by helloyangy** [xai-org/grok-1#44]

**Comment by rudyrdx** [comment]
314b param, 16bit per float, "a" gpu ?

**Comment by yuhanchen0311** [comment]
you need a cluster of gpus

**Comment by trholding** [comment]
Please move to close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:

https://github.com/xai-org/grok-1/issues/69
