### ISSUE TITLE
We newbies need more information about how to install and run them in windows/mac/linux system.

### ISSUE THREAD

**Issue by tbwork** [xai-org/grok-1#52]
Musk's goal is to liberate human productivity by sharing this LLM with everyone, not just for those experts.
I think the most important part is to let thousands of programmers to join in first.
But we don't even have a hello-world demo for now.
I'd like to help to write documents, and wish to have much more information.
Do you have other sites or tutorials?

**Comment by yarodevuci** [comment]
a video would help as well

**Comment by trholding** [comment]
Please move to close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:

https://github.com/xai-org/grok-1/issues/69
