### ISSUE TITLE
What kind of computer configuration can run this model locally? Can a 3080 do it?

### ISSUE THREAD

**Issue by wgqhandsome** [xai-org/grok-1#60]

**Comment by yarodevuci** [comment]
See answers in another thread

**Comment by amao12580** [comment]
8 x H100（80GB）

**Comment by gxmlfx** [comment]
You need to know is a 314B model

**Comment by trholding** [comment]
Please move to close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:

https://github.com/xai-org/grok-1/issues/69
