### ISSUE TITLE
⚠️ [Rule 69]: Make Love, not SPAM! ⚠️

### ISSUE THREAD

**Issue by trholding** [xai-org/grok-1#69]
### Rule 69: Make Love, not SPAM! 
Github issues are meant to point out issues with code such as bugs or other development and running related problems, suggestions etc. Avoid duplicate issues by searching first and if it the same issue exists, add to that thread. General talks should be carried out in Discussions: 

https://github.com/xai-org/grok-1/discussions 

Issues is not a place like X, adding more issues causes issue spam. More Noise, less signal. So I kindly request you to close all non issues and move to discussions, or even better if it has nothing to do with making grok-1 work on systems or technical stuff, then it is best suited to be posted on X.

There is a real staff engineer out here who is doing some cool stuff at xAI, but adding spam makes him less productive as he has to be glued to github issues and close them. Please make his life easy :)

### ⚠️ 亲爱的新用户，请使用“讨论”功能来避免产生垃圾邮件打扰开发者 ⚠️

Chinese Users, please see: https://github.com/xai-org/grok-1/issues/108

### Useful Discussions / Issues:

[⬇️ [HOWTO]: Downloading grok-1 model | 下载 grok-1 模型](https://github.com/xai-org/grok-1/discussions/129)
[🤖 [INFO]: Minimum Hardware / Working Setups ⚡](https://github.com/xai-org/grok-1/discussions/183)
[🤖 Now run grok-1 with less than 🔲 420 G VRAM ⚡](https://github.com/xai-org/grok-1/issues/42)

**Comment by FallCheetah7373** [comment]
I would recommend pinning this, otherwise it may get buried as more users report newer issues.

**Comment by ldoubil** [comment]
广告无处不在🤣

**Comment by millerhamburger** [comment]
😂

**Comment by EwoutH** [comment]
Maybe this can help: https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository

> Limit to existing users: Limits activity for users with accounts that are less than 24 hours old who do not have prior contributions and are not collaborators.

It should at least block out some of the spam.

Also just directly close irrelevant issues, don’t bother asking users to do it.

**Comment by trholding** [comment]
Good ideas. I am not staff, so can't directly close - just doing public service. I did the current initial batch of close requests with back reference to this issue so that new folks posting get an idea how irrelevant issues / spam looks like and to avoid it. And I think new users got the point so wont need to ask people to close issues :)

**Comment by EwoutH** [comment]
@xSetech this could maybe help you make the repo a bit more manageable :)

**Comment by xSetech** [comment]
@EwoutH Done

@trholding Thanks for your help!

**Comment by trholding** [comment]
> @EwoutH Done
> 
> @trholding Thanks for your help!

@xSetech Thanks for the good work! Gratitude to the whole xAI team for taking a step towards true open AI!

**Comment by bingxinti** [comment]
愿景科技有限公司 朱工 前来祝贺，发来亲切慰问和真挚的祝福， 祝愿所有企业统统遥遥领先！！！
愿景科技有限公司 朱工 前来祝贺，发来亲切慰问和真挚的祝福， 祝愿所有企业统统遥遥领先！！！
愿景科技有限公司 朱工 前来祝贺，发来亲切慰问和真挚的祝福， 祝愿所有企业统统遥遥领先！！！
