### ISSUE TITLE
Sex

### ISSUE THREAD

**Issue by Rorg562w** [xai-org/grok-1#72]

**Comment by trholding** [comment]
Closest thing to that is issue #69 

Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:

https://github.com/xai-org/grok-1/issues/69

**Comment by MartinPeris** [comment]
LOL Sex: not planned now xD

**Comment by nonetrix** [comment]
>No official rp grok fine tune so I can't have cat girl waifu like Elon promised 
Elon failed us it's grokover
