### ISSUE TITLE
Are there plans to develop on the pytorch framework?

### ISSUE THREAD

**Issue by JasonCZH4** [xai-org/grok-1#74]
Are there plans to develop on the pytorch framework? Many LLM develop based on torch, like LLama, Qwen, etc. Some developers may not be familiar with JAX.

**Comment by AsureDay** [comment]
is there any problem?

**Comment by dominiquegarmier** [comment]
I created a demo pytorch implementation https://github.com/DominiqueGarmier/grok-pytorch you can't really run it at the moment. Maybe it's a good starting point if someone wants to create a full pytorch version.
