### ISSUE TITLE
SOS！not relative but important for me !

### ISSUE THREAD

**Issue by cxy99zyr** [xai-org/grok-1#79]
I'm trying to make superpoint's vgg_bakcbone better , so i used depthwiseconv2d and try so many methods ,but it seems that it doesn't work, im confused ,could someone can help me  to improve superpoint or give me some good advice?thanks!,by the way,im a lgbt!

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:

https://github.com/xai-org/grok-1/issues/69
