### ISSUE TITLE
pip install -r requirements.txt broken

### ISSUE THREAD

**Issue by SleepTheGod** [xai-org/grok-1#83]
`root@localhost:~/grok-1# pip install -r requirements.txt
Collecting dm_haiku==0.0.12 (from -r requirements.txt (line 1))
  Downloading dm_haiku-0.0.12-py3-none-any.whl.metadata (19 kB)
Collecting jax==0.4.25 (from jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2))
  Downloading jax-0.4.25-py3-none-any.whl.metadata (24 kB)
Collecting numpy==1.26.4 (from -r requirements.txt (line 3))
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 13.1 MB/s eta 0:00:00
Collecting sentencepiece==0.2.0 (from -r requirements.txt (line 4))
  Downloading sentencepiece-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting absl-py>=0.7.1 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting jmp>=0.0.2 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Downloading jmp-0.0.4-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.11/dist-packages (from dm_haiku==0.0.12->-r requirements.txt (line 1)) (0.8.10)
Collecting flax>=0.7.1 (from dm_haiku==0.0.12->-r requirements.txt (line 1))
  Downloading flax-0.8.2-py3-none-any.whl.metadata (10 kB)
Collecting ml-dtypes>=0.2.0 (from jax==0.4.25->jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2))
  Downloading ml_dtypes-0.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting opt-einsum (from jax==0.4.25->jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2))
  Downloading opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: scipy>=1.9 in /usr/lib/python3/dist-packages (from jax==0.4.25->jax[cuda12_pip]==0.4.25->-r requirements.txt (line 2)) (1.10.1)
INFO: pip is looking at multiple versions of jax[cuda12-pip] to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip" (from jax[cuda12-pip]) (from versions: 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25)
ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89; extra == "cuda12_pip"
root@localhost:~/grok-1#`

**Comment by superswan** [comment]
clumsy lol.  there's already issue for this 

#24
