### ISSUE TITLE
What are the minimum hardware requirements for testing this code

### ISSUE THREAD

**Issue by chenzhipenga** [xai-org/grok-1#86]
What are the minimum hardware requirements for testing this code

**Comment by Konard** [comment]
I have already asked that question at https://github.com/xai-org/grok-1/issues/62

**Comment by xuzeyu91** [comment]
According to rumors, we need 8 H100

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108 

Also duplicate of #62
