### ISSUE TITLE
Is grok api is available

### ISSUE THREAD

**Issue by jahidhasanlinix** [xai-org/grok-1#89]
Hi, I have one question. Does grok ai api is publicly available to use it for some SaaS application, unlike OpenAI API? Or, grok ai is not planning to make it it available to use for software application to use in commercial products?

**Comment by Konard** [comment]
[gRPC API](https://developers.x.ai/api) is available via [Early Access program](https://developers.x.ai/#access).

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108
