### ISSUE TITLE
这玩意有啥实际落地场景？

### ISSUE THREAD

**Issue by johnvi-l** [xai-org/grok-1#94]
用于给其他软件提供接口？

**Comment by DF1024** [comment]
国内一大批自主创新正在路上,缅A的chatgpt概念又要炒起来了

**Comment by fhfengzhiyong** [comment]
正在写ai的行业落地方案，我tm何德何能

**Comment by Bailey-24** [comment]
直接问GPT不就出来了吗？
![image](https://github.com/xai-org/grok-1/assets/72083251/e8777403-e5d3-4366-9101-5de8ad4f4644)

**Comment by Bailey-24** [comment]
> 国内一大批自主创新正在路上,缅A的chatgpt概念又要炒起来了

兄弟打算买哪支，还是直接AI基金

**Comment by FHWWC** [comment]
企业或组织使用该模型，为下面的用户提供服务，收费或付费。
这就不是个人能玩的，大佬除外。

**Comment by dcdlove** [comment]
要点脸吧这里不是让你发表废话的地方，请不要制造垃圾问题

**Comment by telltao** [comment]
请关闭这个废物话题，请不要给开发者造成额外负担谢谢。@johnvi-l

**Comment by wwg502719344** [comment]
遥遥领先

**Comment by yaolunmao** [comment]
我觉得马斯克的开源是很有意义的，参与进来的人多了，自然就会推动ai界的发展

**Comment by JasonPanJ** [comment]
Please fucking close this crap topic, please don't cause extra burden to developers, I fuck you don't lose the face of the Chinese people, thank you @johnvi-l

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108
