### ISSUE TITLE
不知道GTX2070s能否运行?

### ISSUE THREAD

**Issue by 20gg** [xai-org/grok-1#97]
rt

**Comment by youshika881** [comment]
pao ge ji er !

**Comment by bluevisor** [comment]
需要300G以上的显存，8块4090都不够

**Comment by bluemidi** [comment]
估计要大几十张卡插一起才行，你得先找个支持的主板才行，或者分布式部署，那估计很慢很慢，几十秒蹦出来一个字。

**Comment by 20gg** [comment]
贫穷限制了我的想象力,众筹一波

**Comment by bluevisor** [comment]
你需要DGX那种服务器

**Comment by dream80** [comment]
非常需要一个mini版，大家能玩的才是好东西。

**Comment by Tangsonghuai** [comment]
应该可以下载，运行就不可以了

**Comment by bluemidi** [comment]
q2 量化有希望玩下

**Comment by bluevisor** [comment]
Q2有希望能搞到20G以下

**Comment by gotoeasy** [comment]
太麻烦了，希望有心者编译个exe分发下

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108

**Comment by yidao2piaopiao** [comment]
个人，我顶多能抗住两张24G了，那得少多少参呀
