### ISSUE TITLE
300个G得下多久啊？？拉下来直接开个ai公司可以嘛？

### ISSUE THREAD

**Issue by youshika881** [xai-org/grok-1#98]
good good good !

**Comment by bluemidi** [comment]
那你得准备8块H800的卡

**Comment by Bailey-24** [comment]
github人均AI公司老板

**Comment by bluevisor** [comment]
洛杉矶1G的线路下了俩小时

**Comment by Pandolar** [comment]
丢人丢到这了

**Comment by ShawnJim** [comment]
是懂开公司的

**Comment by gotoeasy** [comment]
建议马哥开源服务器让大家用，再开源工程师帮干活，最好把公司开源，这样不但300G不用下载，公司都不用开了

**Comment by bank010** [comment]
> 建议马哥开源服务器让大家用，再开源工程师帮干活，最好把公司开源，这样不但300G不用下载，公司都不用开了

好好好，你是懂源神的

**Comment by gotoeasy** [comment]
> 全世界都在说中国话？哈哈哈

AI世界还有语言区别吗，哈哈

**Comment by dcdlove** [comment]
丢人现眼的玩意，拉屎到卫生间，，，，，这是讨论问题的地方

**Comment by telltao** [comment]
请关闭这个话题，不要给开发者增加额外负担谢谢。

**Comment by tuyaao** [comment]
同胞们 不要在这下面发乱七八糟的东西好吗？

**Comment by telltao** [comment]
请你关闭这个废物话题，请不要给开发者造成额外负担，我去你妈的别丢中国人的脸了，谢谢
Please close this crap topic, please do not create extra burden on developers, I fuck you, thank you

**Comment by Jesus-Yu** [comment]
国内环境，发展不起来活该😁

**Comment by bluevisor** [comment]
关了吧，这条确实不算这个软件的issue.

**Comment by neo-turak** [comment]
Plase close this issue ASAP, due to it is a crap topic.

**Comment by bluevisor** [comment]
there's no need for profanity, please be kind to our new users.

**Comment by 97wow** [comment]
300个G 需要具体时间 要看你的带宽大小，如果是10MB/s，你可能需要大概500分钟，即 8个小时左右。
拉下来直接开个AI公司是可以的，当然 这需要你对AI的应用场景进行落地，并且进行有效的相关开发。


这才是issues 的正确使用，而不是看到自己的国人问了一些你们觉得“丢脸”的话，就直接爆粗口 “Please fucking close this crap topic”。

中国人很友好，中国人很团结

不友好的是谁？不团结的又是谁？

**Comment by trholding** [comment]
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
#69 
#108

**Comment by XA2005** [comment]
It's all open source, and there are so many requirements
都开源了要求还那么多，你他妈那的。

**Comment by QAQ707631836** [comment]
你觉得这个问题是它在阴阳还是它脑子不好？

**Comment by QAQ707631836** [comment]
> 300个G 需要具体时间 要看你的带宽大小，如果是10MB/s，你可能需要大概500分钟，即 8个小时左右。 拉下来直接开个AI公司是可以的，当然 这需要你对AI的应用场景进行落地，并且进行有效的相关开发。
> 
> 这才是issues 的正确使用，而不是看到自己的国人问了一些你们觉得“丢脸”的话，就直接爆粗口 “Please fucking close this crap topic”。
> 
> 中国人很友好，中国人很团结
> 
> 不友好的是谁？不团结的又是谁？

你觉得这个问题是它在阴阳还是它脑子不好？

**Comment by yang4515** [comment]
> 300个G 需要具体时间 要看你的带宽大小，如果是10MB/s，你可能需要大概500分钟，即 8个小时左右。 拉下来直接开个AI公司是可以的，当然 这需要你对AI的应用场景进行落地，并且进行有效的相关开发。
> 
> 这才是issues 的正确使用，而不是看到自己的国人问了一些你们觉得“丢脸”的话，就直接爆粗口 “Please fucking close this crap topic”。
> 
> 中国人很友好，中国人很团结
> 
> 不友好的是谁？不团结的又是谁？

心平气和的讲，你说的答案是@youshika881 想要的吗，他真想开公司还差那几个小时的下载时间吗。在这发这个问题就是来找骂的，你仔细想想。

**Comment by dlongs49** [comment]
离谱到家了😂

**Comment by javanst** [comment]
都一个逼样子，谁又能说谁呢

**Comment by zhuwentao666** [comment]
> 300个G 需要具体时间 要看你的带宽大小，如果是10MB/s，你可能需要大概500分钟，即 8个小时左右。 拉下来直接开个AI公司是可以的，当然 这需要你对AI的应用场景进行落地，并且进行有效的相关开发。
> 
> 这才是issues 的正确使用，而不是看到自己的国人问了一些你们觉得“丢脸”的话，就直接爆粗口 “Please fucking close this crap topic”。
> 
> 中国人很友好，中国人很团结
> 
> 不友好的是谁？不团结的又是谁？

他在阴阳怪气看不出来吗？写程序的这点脑子没有？？？？？？？？？

**Comment by telltao** [comment]
> 300个G 需要具体时间 要看你的带宽大小，如果是10MB/s，你可能需要大概500分钟，即 8个小时左右。 拉下来直接开个AI公司是可以的，当然 这需要你对AI的应用场景进行落地，并且进行有效的相关开发。
> 
> 这才是issues 的正确使用，而不是看到自己的国人问了一些你们觉得“丢脸”的话，就直接爆粗口 “Please fucking close this crap topic”。
> 
> 中国人很友好，中国人很团结
> 
> 不友好的是谁？不团结的又是谁？

你难道看不出来它这句话说的什么意思吗？昂？？ 回家卖菜去吧。 你有脑子吗？ @97wow

**Comment by 97wow** [comment]
> 你难道看不出来它这句话说的什么意思吗？昂？？ 回家卖菜去吧。 你有脑子吗？ @97wow

emm，忠言逆耳，感谢能让我了解到我的错误，现在我已经意识到自己的错误了，很抱歉。
从各位的回复中可以看出 确实是我错了

我深刻认识到了自己的思维和立场是有问题的，没能透过表象看本质。
我对所有持反对意见的人表示歉意。
希望这个话题就此结束，至少对我的评价就此结束，我已经认识到了我的错误。

**Comment by Supperzha** [comment]
nb

**Comment by lyy2182** [comment]
幽默
